version: '3'
services:
  data_api:
    image: davidgeismar/artifacts_data_api:latest
    command: 'rails server -b 0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ./log/docker_development.log:/artifacts_data_api/log/docker_development.log
    environment:
      - RAILS_ENV=docker_development
      - SECRET_KEY_BASE=docker_development_secret
  app:
    build: .
    command: 'rails server -p 4000'
    ports:
      - "4000:4000"
    volumes:
      - ./log/production.log:/artifacts_data_api/log/production.log
    environment:
      - RAILS_ENV=docker_development
      - SECRET_KEY_BASE=docker_development_secret
