  version: '3'
  services:
    data_api:
      image: davidgeismar/artifacts_data_api:latest
      command: 'tail -f /dev/null'
      entrypoint: /artifacts_data_api/entrypoint.sh
      ports:
        - "3000:3000"
      volumes:
        - ./log:/artifacts_data_api/log
      environment:
        - RAILS_ENV=production
        - SECRET_KEY_BASE=production_secret
        - DB_PASSWORD=artifacts
        - DB_USERNAME=postgres
        - DB_URL=artifacts-test.cndqyekjgsit.eu-west-3.rds.amazonaws.com
        - DB_PORT=5432
        - DB_NAME=artifacts-test
    app:
      entrypoint: /artifacts/entrypoint.sh
      image: davidgeismar/artifacts-app:latest
      command: 'rails s -p 4000'
      ports:
        - "80:4000"
      volumes:
        - ./log:/artifacts/log
      environment:
        - RAILS_ENV=production
        - SECRET_KEY_BASE=production_secret
        - DB_PASSWORD=artifacts
        - DB_USERNAME=postgres
        - DB_URL=artifacts-test.cndqyekjgsit.eu-west-3.rds.amazonaws.com
        - DB_PORT=5432
        - DB_NAME=artifacts-test
